### ISSUE TITLE
How to add a node?

### ISSUE THREAD

**Issue by sroussey** [clarkmcc/ngraph#32]
In the example for xyflow,  you could do this:

```ts
 const [reactFlowInstance, setReactFlowInstance] = useState<ReactFlowInstance>();
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]);

  const onConnect = (params: Connection | Edge) => setEdges((eds) => addEdge(params, eds));
  const onInit = (rfi: ReactFlowInstance) => setReactFlowInstance(rfi);

  const onDrop = (event: DragEvent) => {
    event.preventDefault();

    if (reactFlowInstance) {
      const type = event.dataTransfer.getData('application/reactflow');
      const position = reactFlowInstance.screenToFlowPosition({
        x: event.clientX,
        y: event.clientY,
      });
      const newNode: Node = {
        id: getId(),
        type,
        position,
        data: { label: `${type} node` },
      };

      setNodes((nds) => nds.concat(newNode));
    }
  };

  return (
    <div className={styles.dndflow}>
      <ReactFlowProvider initialNodes={initialNodes} initialEdges={[]}>
        <div className={styles.wrapper}>
          <ReactFlow
            nodes={nodes}
            edges={edges}
            onEdgesChange={onEdgesChange}
            onNodesChange={onNodesChange}
            onConnect={onConnect}
            onInit={onInit}
            onDrop={onDrop}
            onDragOver={onDragOver}
          >
```

Basically, to add a node, it does `setNodes((nds) => nds.concat(newNode));` but that doesn't work with ngraph. With ngraph, it is managing things separately, and the uses `useGraphStore` which I can not use since I am outside the Provider for it.

Seems like a basic thing. What am I missing?

**Comment by P13612** [comment]
This is what I did. And it works: 
import React, { useState } from 'react';
import './Frame.css';
import {
    useBuildGraphConfig,
    GraphConfigProvider,
    NodeGraphEditor,
} from "@clarkmcc/ngraph";

import {
    Background,
    BackgroundVariant,
    ReactFlowProvider,
} from "@xyflow/react";

import { useDrop } from 'react-dnd';

const TheNodeEditor = () => {
    
    const [nodes, setNodes] = useState([
        { id: "1", type: "workflow", position: { x:  50, y:  50 }, data: {} },
        { id: "2", type: "workflow", position: { x: 400, y: 100 }, data: {} }
    ]);
    const [edges, setEdges] = useState([
        { id: "e1", source: "1", target: "2", sourceHandle: "source", targetHandle: "drain" }
    ]);
    
    const onNodesChange = (changes) => setNodes((nds) => ReactFlow.applyNodeChanges(changes, nds));
    
    const [, drop] = useDrop({
        accept: 'workflow_item',
        drop: (item, monitor) => {
	    console.log('Drop event triggered');
            const delta = monitor.getClientOffset();
            const newId = Math.floor(Math.random() * 900000) + 100000; // Generates a random 6-digit number
            const newNode = {
                id: newId.toString(),
                type: 'workflow',
                position: { x: 100, y: 100 },
                data: {},
            };
	    console.log('New node to be added:', newNode);
	    setNodes(prevNodes => {
		console.log('Current nodes before adding new:', prevNodes);
		console.log('Current nodes with new node:', newNode);
		return [...prevNodes, newNode];
            });
        },
	collect: monitor => {
            console.log('Is over:', monitor.isOver());  // Check if any draggable item is over the target
            return {};
	},
    });
    
    const config = useBuildGraphConfig({
	valueTypes: {
	    string: {
		name: "String",
		color: "#a1a1a1",
		inputType: "value",
		defaultValue: "",
	    },
	    workflow: {
		name: "Workflow",
		color: "#0e826e",
		inputType: null,
	    },
	},
	nodeGroups: {
	    default: {
		name: "Default",
		color: "#600c0c",
	    },
	},
	nodes: {
	    workflow: {
		name: "DAAI Designer Workflow",
		group: "default",
		inputs: [
		    {
			name: "Input",
			id: "source",
			valueType: "string",
		    }
		],
		outputs: [
		    {
			name: "Output",
			id: "drain",
			valueType: "string",
		    },
		],
	    },
	},
    });

    return (
	<div ref={drop} className="container">
	    <ReactFlowProvider>
		<GraphConfigProvider defaultConfig={config}>
		    <NodeGraphEditor
			key={nodes.length}
			defaultNodes={nodes}
			defaultEdges={edges}
			onNodesChange={onNodesChange}
			fitView
		    >
			<Background color="#52525b" variant={BackgroundVariant.Dots} />
		    </NodeGraphEditor>
		</GraphConfigProvider>
	    </ReactFlowProvider>
	</div>
    );
};

export default TheNodeEditor;
